name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Test
        run: cargo test

      - name: Get Version
        run: |
          export VERSION=$(cat Cargo.toml | grep version | cut -d ' ' -f 3 | sed 's/"//g')
          echo VERSION=$VERSION >> $GITHUB_ENV
          sed -i "s/VERSION/$VERSION/" PKGBUILD

      - name: Publish AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: toru
          pkgbuild: PKGBUILD
          commit_username: pryoscode
          commit_email: info@pryoscode.net
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: v${{ env.VERSION }}
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519

      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}